language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jakubkot/docker-react -f Dockerfile.dev . #-t = tag

script:
  - docker run -e CI=true jakubkot/docker-react npm run test -- --coverage # -e CI=true = exit

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-411335089205"
  bucket_path: "docker-react" # dpmyślnie takie samo jak app
